name: Admin Web
description: 어드민 웹 관련 이슈
title: "[Admin] "
labels: ["admin", "frontend"]
body:
  - type: dropdown
    id: type
    attributes:
      label: 타입
      options:
        - Feature
        - Bug
        - UI/UX
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 카테고리
      options:
        - 대시보드
        - 예산 관리
        - 상품 관리
        - 주문 내역
        - 기타

  - type: textarea
    id: description
    attributes:
      label: 설명
      placeholder: 무엇을 구현/수정하나요?
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 완료 조건
      placeholder: |
        - [ ]
        - [ ]
